export const allSubDistrict = () => {
  return [
    'Amtali',
    'Bamna',
    'Barguna Sadar',
    'Betagi',
    'Patharghata',
    'Taltali',
    'Agailjhara',
    'Babuganj',
    'Bakerganj',
    'Banaripara',
    'Gaurnadi',
    'Hizla',
    'Barishal Sadar',
    'Mehendiganj',
    'Muladi',
    'Wazirpur',
    'Bhola Sadar',
    'Burhanuddin',
    'Char Fasson',
    'Daulatkhan',
    'Lalmohan',
    'Manpura',
    'Tazumuddin',
    'Jhalokati Sadar',
    'Kathalia',
    'Nalchity',
    'Rajapur',
    'Bauphal',
    'Dashmina',
    'Galachipa',
    'Kalapara',
    'Mirzaganj',
    'Patuakhali Sadar',
    'Rangabali',
    'Dumki',
    'Bhandaria',
    'Kawkhali',
    'Mathbaria',
    'Nazirpur',
    'Pirojpur Sadar',
    'Nesarabad (Swarupkati)',
    'Zianagar',
    'Ali Kadam',
    'Bandarban Sadar',
    'Lama',
    'Naikhongchhari',
    'Rowangchhari',
    'Ruma',
    'Thanchi',
    'Akhaura',
    'Bancharampur',
    'Brahmanbaria Sadar',
    'Kasba',
    'Nabinagar',
    'Nasirnagar',
    'Sarail',
    'Ashuganj',
    'Bijoynagar',
    'Chandpur Sadar',
    'Faridganj',
    'Haimchar',
    'Haziganj',
    'Kachua',
    'Matlab Dakshin',
    'Matlab Uttar',
    'Shahrasti',
    'Anwara',
    'Banshkhali',
    'Boalkhali',
    'Chandanaish',
    'Fatikchhari',
    'Hathazari',
    'Karnaphuli',
    'Lohagara',
    'Mirsharai',
    'Patiya',
    'Rangunia',
    'Raozan',
    'Sandwip',
    'Satkania',
    'Sitakunda',
    'Bandar',
    'Chandgaon',
    'Double Mooring',
    'Kotwali',
    'Pahartali',
    'Panchlaish',
    'Bhujpur',
    'Barura',
    'Brahmanpara',
    'Burichang',
    'Chandina',
    'Chauddagram',
    'Daudkandi',
    'Debidwar',
    'Homna',
    'Laksam',
    'Muradnagar',
    'Nangalkot',
    'Cumilla Adarsha Sadar',
    'Meghna',
    'Titas',
    'Monohargonj',
    'Cumilla Sadar Dakshin',
    'Chakaria',
    "Cox's Bazar Sadar",
    'Kutubdia',
    'Maheshkhali',
    'Ramu',
    'Teknaf',
    'Ukhia',
    'Pekua',
    'Chhagalnaiya',
    'Daganbhuiyan',
    'Feni Sadar',
    'Parshuram',
    'Sonagazi',
    'Fulgazi',
    'Dighinala',
    'Khagrachhari',
    'Lakshmichhari',
    'Mahalchhari',
    'Manikchhari',
    'Matiranga',
    'Panchhari',
    'Ramgarh',
    'Lakshmipur Sadar',
    'Raipur',
    'Ramganj',
    'Ramgati',
    'Kamalnagar',
    'Begumganj',
    'Noakhali Sadar',
    'Chatkhil',
    'Companiganj',
    'Hatiya',
    'Senbagh',
    'Sonaimuri',
    'Subarnachar',
    'Kabirhat',
    'Bagaichhari',
    'Barkal',
    'Kawkhali (Betbunia)',
    'Belaichhari',
    'Kaptai',
    'Juraichhari',
    'Langadu',
    'Naniyachar',
    'Rajasthali',
    'Rangamati Sadar',
    'Amtali',
    'Bamna',
    'Barguna Sadar',
    'Betagi',
    'Patharghata',
    'Taltali',
    'Agailjhara',
    'Babuganj',
    'Bakerganj',
    'Banaripara',
    'Gaurnadi',
    'Hizla',
    'Barishal Sadar',
    'Mehendiganj',
    'Muladi',
    'Wazirpur',
    'Bhola Sadar',
    'Burhanuddin',
    'Char Fasson',
    'Daulatkhan',
    'Lalmohan',
    'Manpura',
    'Tazumuddin',
    'Jhalokati Sadar',
    'Kathalia',
    'Nalchity',
    'Rajapur',
    'Bauphal',
    'Dashmina',
    'Galachipa',
    'Kalapara',
    'Mirzaganj',
    'Patuakhali Sadar',
    'Rangabali',
    'Dumki',
    'Bhandaria',
    'Kawkhali',
    'Mathbaria',
    'Nazirpur',
    'Pirojpur Sadar',
    'Nesarabad (Swarupkati)',
    'Zianagar',
    'Ali Kadam',
    'Bandarban Sadar',
    'Lama',
    'Naikhongchhari',
    'Rowangchhari',
    'Ruma',
    'Thanchi',
    'Akhaura',
    'Bancharampur',
    'Brahmanbaria Sadar',
    'Kasba',
    'Nabinagar',
    'Nasirnagar',
    'Sarail',
    'Ashuganj',
    'Bijoynagar',
    'Chandpur Sadar',
    'Faridganj',
    'Haimchar',
    'Haziganj',
    'Kachua',
    'Matlab Dakshin',
    'Matlab Uttar',
    'Shahrasti',
    'Anwara',
    'Banshkhali',
    'Boalkhali',
    'Chandanaish',
    'Fatikchhari',
    'Hathazari',
    'Karnaphuli',
    'Lohagara',
    'Mirsharai',
    'Patiya',
    'Rangunia',
    'Raozan',
    'Sandwip',
    'Satkania',
    'Sitakunda',
    'Bandar',
    'Chandgaon',
    'Double Mooring',
    'Kotwali',
    'Pahartali',
    'Panchlaish',
    'Bhujpur',
    'Barura',
    'Brahmanpara',
    'Burichang',
    'Chandina',
    'Chauddagram',
    'Daudkandi',
    'Debidwar',
    'Homna',
    'Laksam',
    'Muradnagar',
    'Nangalkot',
    'Cumilla Adarsha Sadar',
    'Meghna',
    'Titas',
    'Monohargonj',
    'Cumilla Sadar Dakshin',
    'Chakaria',
    "Cox's Bazar Sadar",
    'Kutubdia',
    'Maheshkhali',
    'Ramu',
    'Teknaf',
    'Ukhia',
    'Pekua',
    'Chhagalnaiya',
    'Daganbhuiyan',
    'Feni Sadar',
    'Parshuram',
    'Sonagazi',
    'Fulgazi',
    'Dighinala',
    'Khagrachhari',
    'Lakshmichhari',
    'Mahalchhari',
    'Manikchhari',
    'Matiranga',
    'Panchhari',
    'Ramgarh',
    'Lakshmipur Sadar',
    'Raipur',
    'Ramganj',
    'Ramgati',
    'Kamalnagar',
    'Begumganj',
    'Noakhali Sadar',
    'Chatkhil',
    'Companiganj',
    'Hatiya',
    'Senbagh',
    'Sonaimuri',
    'Subarnachar',
    'Kabirhat',
    'Bagaichhari',
    'Barkal',
    'Kawkhali (Betbunia)',
    'Belaichhari',
    'Kaptai',
    'Juraichhari',
    'Langadu',
    'Naniyachar',
    'Rajasthali',
    'Rangamati Sadar',
    'Dhamrai',
    'Dohar',
    'Keraniganj',
    'Nawabganj',
    'Savar',
    'Tejgaon Circle',
    'Alfadanga',
    'Bhanga',
    'Boalmari',
    'Charbhadrasan',
    'Faridpur Sadar',
    'Madhukhali',
    'Nagarkanda',
    'Sadarpur',
    'Saltha',
    'Gazipur Sadar',
    'Kaliakair',
    'Kaliganj',
    'Kapasia',
    'Sreepur',
    'Gopalganj Sadar',
    'Kashiani',
    'Kotalipara',
    'Muksudpur',
    'Tungipara',
    'Austagram',
    'Bajitpur',
    'Bhairab',
    'Hossainpur',
    'Itna',
    'Karimganj',
    'Katiadi',
    'Kishoreganj Sadar',
    'Kuliarchar',
    'Mithamain',
    'Nikli',
    'Pakundia',
    'Rajoir',
    'Madaripur Sadar',
    'Kalkini',
    'Shibchar',
    'Daulatpur',
    'Ghior',
    'Harirampur',
    'Manikgonj Sadar',
    'Saturia',
    'Shivalaya',
    'Singair',
    'Gazaria',
    'Lohajang',
    'Munshiganj Sadar',
    'Sirajdikhan',
    'Sreenagar',
    'Tongibari',
    'Araihazar',
    'Bandar',
    'Narayanganj Sadar',
    'Rupganj',
    'Sonargaon',
    'Narsingdi Sadar',
    'Belabo',
    'Monohardi',
    'Palash',
    'Raipura',
    'Shibpur',
    'Baliakandi',
    'Goalandaghat',
    'Pangsha',
    'Rajbari Sadar',
    'Kalukhali',
    'Bhedarganj',
    'Damudya',
    'Gosairhat',
    'Naria',
    'Shariatpur Sadar',
    'Zajira',
    'Shakhipur',
    'Gopalpur',
    'Basail',
    'Bhuapur',
    'Delduar',
    'Ghatail',
    'Kalihati',
    'Madhupur',
    'Mirzapur',
    'Nagarpur',
    'Sakhipur',
    'Dhanbari',
    'Tangail Sadar',
    'Bagerhat Sadar',
    'Chitalmari',
    'Fakirhat',
    'Kachua',
    'Mollahat',
    'Mongla',
    'Morrelganj',
    'Rampal',
    'Sarankhola',
    'Alamdanga',
    'Chuadanga Sadar',
    'Damurhuda',
    'Jibannagar',
    'Abhaynagar',
    'Bagherpara',
    'Chaugachha',
    'Jhikargachha',
    'Keshabpur',
    'Jashore Sadar',
    'Manirampur',
    'Sharsha',
    'Harinakunda',
    'Jhenaidah Sadar',
    'Kaliganj',
    'Kotchandpur',
    'Maheshpur',
    'Shailkupa',
    'Batiaghata',
    'Dacope',
    'Dumuria',
    'Dighalia',
    'Koyra',
    'Paikgachha',
    'Phultala',
    'Rupsha',
    'Terokhada',
    'Daulatpur',
    'Khalishpur',
    'Khan Jahan Ali',
    'Kotwali',
    'Sonadanga',
    'Harintana',
    'Bheramara',
    'Daulatpur',
    'Khoksa',
    'Kumarkhali',
    'Kushtia Sadar',
    'Mirpur',
    'Magura Sadar',
    'Mohammadpur',
    'Shalikha',
    'Sreepur',
    'Gangni',
    'Meherpur Sadar',
    'Mujibnagar',
    'Kalia',
    'Lohagara',
    'Narail Sadar',
    'Naragati',
    'Assasuni',
    'Debhata',
    'Kalaroa',
    'Kaliganj',
    'Satkhira Sadar',
    'Shyamnagar',
    'Tala',
    'Baksiganj',
    'Dewanganj',
    'Islampur',
    'Jamalpur Sadar',
    'Madarganj',
    'Melandaha',
    'Sarishabari',
    'Trishal',
    'Dhobaura',
    'Fulbaria',
    'Gaffargaon',
    'Gauripur',
    'Haluaghat',
    'Ishwarganj',
    'Mymensingh Sadar',
    'Muktagachha',
    'Nandail',
    'Phulpur',
    'Bhaluka',
    'Tara Khanda',
    'Atpara',
    'Barhatta',
    'Durgapur',
    'Khaliajuri',
    'Kalmakanda',
    'Kendua',
    'Madan',
    'Mohanganj',
    'Netrokona Sadar',
    'Purbadhala',
    'Jhenaigati',
    'Nakla',
    'Nalitabari',
    'Sherpur Sadar',
    'Sreebardi',
    'Adamdighi',
    'Bogura Sadar',
    'Dhunat',
    'Dhupchanchia',
    'Gabtali',
    'Kahaloo',
    'Nandigram',
    'Sariakandi',
    'Shajahanpur',
    'Sherpur',
    'Shibganj',
    'Sonatola',
    'Bholahat',
    'Gomastapur',
    'Nachole',
    'Nawabganj Sadar',
    'Shibganj',
    'Akkelpur',
    'Joypurhat Sadar',
    'Kalai',
    'Khetlal',
    'Panchbibi',
    'Atrai',
    'Badalgachhi',
    'Manda',
    'Dhamoirhat',
    'Mohadevpur',
    'Naogaon Sadar',
    'Niamatpur',
    'Patnitala',
    'Porsha',
    'Raninagar',
    'Sapahar',
    'Bagatipara',
    'Baraigram',
    'Gurudaspur',
    'Lalpur',
    'Natore Sadar',
    'Singra',
    'Naldanga',
    'Atgharia',
    'Bera',
    'Bhangura',
    'Chatmohar',
    'Faridpur',
    'Ishwardi',
    'Pabna Sadar',
    'Santhia',
    'Sujanagar',
    'Bagha',
    'Bagmara',
    'Charghat',
    'Durgapur',
    'Godagari',
    'Mohanpur',
    'Paba',
    'Puthia',
    'Tanore',
    'Belkuchi',
    'Chauhali',
    'Kamarkhanda',
    'Kazipur',
    'Raiganj',
    'Shahjadpur',
    'Sirajganj Sadar',
    'Tarash',
    'Ullahpara',
    'Birampur',
    'Birganj',
    'Biral',
    'Bochaganj',
    'Chirirbandar',
    'Phulbari',
    'Ghoraghat',
    'Hakimpur',
    'Kaharole',
    'Khansama',
    'Dinajpur Sadar',
    'Nawabganj',
    'Parbatipur',
    'Phulchhari',
    'Gaibandha Sadar',
    'Gobindaganj',
    'Palashbari',
    'Sadullapur',
    'Sughatta',
    'Sundarganj',
    'Bhurungamari',
    'Char Rajibpur',
    'Chilmari',
    'Phulbari',
    'Kurigram Sadar',
    'Nageshwari',
    'Rajarhat',
    'Raomari',
    'Ulipur',
    'Aditmari',
    'Hatibandha',
    'Kaliganj',
    'Lalmonirhat Sadar',
    'Patgram',
    'Dimla',
    'Domar',
    'Jaldhaka',
    'Kishoreganj',
    'Nilphamari Sadar',
    'Saidpur',
    'Atwari',
    'Boda',
    'Debiganj',
    'Panchagarh Sadar',
    'Tetulia',
    'Badarganj',
    'Gangachhara',
    'Kaunia',
    'Rangpur Sadar',
    'Mithapukur',
    'Pirgachha',
    'Pirganj',
    'Taraganj',
    'Baliadangi',
    'Haripur',
    'Pirganj',
    'Ranisankail',
    'Thakurgaon Sadar',
    'Ajmiriganj',
    'Bahubal',
    'Baniyachong',
    'Chunarughat',
    'Habiganj Sadar',
    'Lakhai',
    'Madhabpur',
    'Nabiganj',
    'Sayestaganj',
    'Barlekha',
    'Juri',
    'Kamalganj',
    'Kulaura',
    'Moulvibazar Sadar',
    'Rajnagar',
    'Sreemangal',
    'Bishwamvarpur',
    'Chhatak',
    'Dakshin Sunamganj',
    'Derai',
    'Dharamapasha',
    'Dowarabazar',
    'Jagannathpur',
    'Jamalganj',
    'Sullah',
    'Sunamganj Sadar',
    'Tahirpur',
    'Balaganj',
    'Beanibazar',
    'Bishwanath',
    'Companigonj',
    'Dakshin Surma',
    'Fenchuganj',
    'Golapganj',
    'Gowainghat',
    'Jaintiapur',
    'Kanaighat',
    'Osmani Nagar',
    'Sylhet Sadar',
    'Zakiganj',
  ];
};
